/*
 * This source file was generated by the Gradle 'init' task
 */
package io.yamsergey.adt.workspace.kotlin;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
