/*
 * This source file was generated by the Gradle 'init' task
 */
package io.yamsergey.adt.workspace.kotlin.cli;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(name = "workspace-kotlin-cli",
         mixinStandardHelpOptions = true,
         version = "workspace-kotlin-cli 1.0",
         description = "Kotlin workspace CLI application")
public class App implements Runnable {

    @Option(names = {"-v", "--verbose"}, description = "Verbose mode")
    private boolean verbose = false;

    @Option(names = {"-n", "--name"}, description = "Name to greet")
    private String name = "World";

    @Parameters(arity = "0..*", description = "Additional parameters")
    private String[] parameters = new String[0];

    @Override
    public void run() {
        if (verbose) {
            System.out.println("Running in verbose mode");
            System.out.println("Parameters: " + java.util.Arrays.toString(parameters));
        }
        System.out.println("Hello " + name + "!");
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}
