name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Build CLI distribution
        run: ./gradlew :adt-cli:installDist

      - name: Package adt-cli
        run: |
          cd adt-cli/build/install
          tar -czf adt-cli-${{ github.ref_name }}.tar.gz adt-cli
          zip -r adt-cli-${{ github.ref_name }}.zip adt-cli
          mv adt-cli-${{ github.ref_name }}.tar.gz ../../../
          mv adt-cli-${{ github.ref_name }}.zip ../../../

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            adt-cli-${{ github.ref_name }}.tar.gz
            adt-cli-${{ github.ref_name }}.zip
          body: |
            ## Android Development Tools ${{ github.ref_name }}

            ### Downloads

            **adt-cli** - Unified CLI for Android project analysis and workspace generation
            - Linux/macOS: `adt-cli-${{ github.ref_name }}.tar.gz` (~114MB)
            - Windows: `adt-cli-${{ github.ref_name }}.zip` (~114MB)

            ### Installation

            ```bash
            # Extract the archive
            tar -xzf adt-cli-${{ github.ref_name }}.tar.gz
            ```

            ### Usage

            ```bash
            # Generate workspace.json for Kotlin LSP
            adt-cli/bin/adt-cli workspace /path/to/android/project \
              --output workspace.json

            # Analyze project structure
            adt-cli/bin/adt-cli resolve /path/to/android/project \
              --workspace --output project-analysis.json

            # List build variants
            adt-cli/bin/adt-cli resolve /path/to/android/project \
              --variants --output variants.json
            ```

            ### Requirements

            - Java 21 or higher
            - Gradle 8.0 or higher (for analyzed projects)
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
